export default [
    { parts: ["In the next twelve months, we are going to intentionally deprioritize ", " based on evidence that ", ". We’ll revisit this decision periodically, and be on the lookout for ", "."] },
    { parts: ["While our competitors get distracted by ", " we’ll stay focused on ", ". While they focus on ", " we’ll allow ourselves to diverge and explore new ways to ", "."] },
    { parts: ["There’s a counterintuitive element to the question of whether to", "or", ". And that’s that"] },
    { parts: ["We need to ", " before ", ". If we don’t, we run the risk of ", "."] },
    { parts: ["We have flexibility when it comes to ", "But if we don’t", "in the next", "we’ll be in less of a position to use that flexibility to our advantage."] },
    { parts: ["We are admittedly less experienced at", ". But we do know", "and we can", ". So there may be more options here than we think."] },
    { parts: ["Despite our many disadvantages when it comes to", "I do believe we have leverage when it comes to", ". This will not be easy, but there’s an opportunity to"] },
    { parts: ["While competitors are going to zig by", "we’re going to try to zag by", ". We believe that will", "despite signals that"] },
    { parts: ["Our key strategy is to turn the game of", "into a game of"] },
    { parts: ["The riskiest assumption we are operating under at the moment is that", ". If we’re wrong, it could significantly impact the business because"] },
    { parts: ["Until now we’ve been able to", ". Now, because", "it will be necessary to change our approach to something more", "and less"] },
    { parts: ["It is vital to start laying the groundwork for", ". In the near-term we can get away with not", ". But it will eventually come back to bite us."] },
    { parts: ["A key part of our strategy is to ignore ", " despite pressure to ", ". This will be challenging because ", " but ultimately we believe it will pay off because ", "."] },
    { parts: ["Pundits believe that", ". They’re right that", "but I believe they are wrong about", "because they are missing the insight that"] },
];